### ISSUE TITLE
Exception when requiring monger.credentials

### ISSUE THREAD

**Issue by kkneutgen** [michaelklishin/monger#107]
Hi,

requiring [monger.credentials :as mcred] works well with the repl - but leads to a NullPointerException while trying to create an uberjar with lein.

I tried to comment out any further code, the Exception is still thrown as long as monger.credentails is required.

```
(ns appxy.db
  (:refer-clojure :exclude [remove])
  (:require
            [monger.db]
            [monger.core :as mg]
            [monger.query :as mq]
            [monger.collection :as mc]
            [monger.operators :refer :all]
            [monger.credentials :as mcred]
  (:import 
           [com.mongodb MongoOptions ServerAddress]
           [org.bson.types ObjectId]
           [com.mongodb DB WriteConcern]))


WARNING: for already refers to: #'clojure.core/for in namespace: monger.credentials, being replaced by: #'monger.credentials/for
java.lang.NullPointerException, compiling:(db.clj:1:1)
        at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3558)
        at clojure.lang.Compiler.compile1(Compiler.java:7226)
        at clojure.lang.Compiler.compile1(Compiler.java:7216)
        at clojure.lang.Compiler.compile(Compiler.java:7292)
        at clojure.lang.RT.compile(RT.java:398)
        at clojure.lang.RT.load(RT.java:438)
        at clojure.lang.RT.load(RT.java:411)
        at clojure.core$load$fn__5066.invoke(core.clj:5641)
        at clojure.core$load.doInvoke(core.clj:5640)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invoke(core.clj:5446)
        at clojure.core$compile$fn__5071.invoke(core.clj:5652)
        at clojure.core$compile.invoke(core.clj:5651)
        at user$eval9$fn__16.invoke(form-init9078884707663483923.clj:1)
        at user$eval9.invoke(form-init9078884707663483923.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6703)
        at clojure.lang.Compiler.eval(Compiler.java:6693)
        at clojure.lang.Compiler.load(Compiler.java:7130)
        at clojure.lang.Compiler.loadFile(Compiler.java:7086)
        at clojure.main$load_script.invoke(main.clj:274)
        at clojure.main$init_opt.invoke(main.clj:279)
        at clojure.main$initialize.invoke(main.clj:307)
        at clojure.main$null_opt.invoke(main.clj:342)
        at clojure.main$main.doInvoke(main.clj:420)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
```

**Comment by michaelklishin** [comment]
```
WARNING: for already refers to: #'clojure.core/for in namespace: monger.credentials, being replaced by: #'monger.credentials/for
```

suggests you refer to `monger.credentials` in your own code. That shadows `clojure.core/for`.

**Comment by kkneutgen** [comment]
Sorry, I referred to monger.credentials like the docs say:

(ns monger.docs.examples
  (:require [monger.core :as mg]
            [monger.credentials :as mcred]))

(let [db   "some-db"
      u    "username"
      p    "password"]
  (mg/connect-with-credentials "127.0.0.1" (mcred/for u db p))
