### ISSUE TITLE
How to connect to mongodb from c9.io?

### ISSUE THREAD

**Issue by salmazov** [michaelklishin/monger#136]
I use c9.io for my everyday coding. I want to connect to mongodb, but I receive this error:

user=> May 04, 2016 1:18:46 PM com.mongodb.diagnostics.logging.JULLogger log
INFO: Exception in monitor thread while connecting to server localhost:28017
com.mongodb.MongoSocketReadException: Prematurely reached end of stream
        at com.mongodb.connection.SocketStream.read(SocketStream.java:88)
        at com.mongodb.connection.InternalStreamConnection.receiveResponseBuffers(InternalStreamConnection.java:491)
        at com.mongodb.connection.InternalStreamConnection.receiveMessage(InternalStreamConnection.java:221)
        at com.mongodb.connection.CommandHelper.receiveReply(CommandHelper.java:134)
        at com.mongodb.connection.CommandHelper.receiveCommandResult(CommandHelper.java:121)
        at com.mongodb.connection.CommandHelper.executeCommand(CommandHelper.java:32)
        at com.mongodb.connection.InternalStreamConnectionInitializer.initializeConnectionDescription(InternalStreamConnectionInitializer.java:83)
        at com.mongodb.connection.InternalStreamConnectionInitializer.initialize(InternalStreamConnectionInitializer.java:43)
        at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:115)
        at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:128)
        at java.lang.Thread.run(Thread.java:745)

**Comment by michaelklishin** [comment]
Please ask questions on the mailing list. The exception is an indication of an I/O (so, likely TCP connectivity) issue of some kind but it is very generic. See MongoDB logs, maybe it has something. Anyhow, I don't use GitHub issues for questions if I can help it.
