### ISSUE TITLE
Startup time in repl is at least 17 secs

### ISSUE THREAD

**Issue by danceasarxx** [michaelklishin/monger#152]
I am trying using monger in a ring + compojure web application. Once I start `lein repl` and `require` any namespace that uses monger(any of the namespaces from core....query) It takes a minimum of `17 secs` before it shows `nil`. If I happen to press `Ctrl + C` while it is requiring it reports this after some time.

```java
Jan 05, 2017 3:51:29 AM org.bson.types.ObjectId createProcessIdentifier
WARNING: Failed to get process identifier from JMX, using random number instead
java.lang.ThreadDeath
	at java.lang.Thread.stop(Thread.java:850)
	at clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__4130.invoke(interruptible_eval.clj:243)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__3861.invoke(middleware.clj:22)
	at clojure.tools.nrepl.middleware.load_file$wrap_load_file$fn__4254.invoke(load_file.clj:79)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__3861.invoke(middleware.clj:22)
	at coreclj.core$eval4586$fn__4587$fn__4589.invoke(form-init5887639264879908142.clj:1)
	at clojure.tools.nrepl.middleware.pr_values$pr_values$fn__4048.invoke(pr_values.clj:22)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__3861.invoke(middleware.clj:22)
	at clojure.tools.nrepl.middleware.session$add_stdin$fn__4211.invoke(session.clj:238)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__3861.invoke(middleware.clj:22)
	at clojure.tools.nrepl.middleware.session$session$fn__4196.invoke(session.clj:192)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__3861.invoke(middleware.clj:22)
	at clojure.tools.nrepl.server$handle_STAR_.invokeStatic(server.clj:19)
	at clojure.tools.nrepl.server$handle_STAR_.invoke(server.clj:16)
	at clojure.tools.nrepl.server$handle$fn__4267.invoke(server.clj:28)
	at clojure.core$binding_conveyor_fn$fn__4676.invoke(core.clj:1938)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by michaelklishin** [comment]
Clojure code is compiled when loaded. `java.lang.ThreadDeath` from nREPL middleware has nothing to do with Monger and most likely what you get if you interrupt the compiler.

**Comment by danceasarxx** [comment]
That's my point. I had to interrupt it to see why it was and is still taking so long to require monger. My problem's not the exception, my problem is the time it takes to require monger.

**Comment by danceasarxx** [comment]
And this is not a question....I am reporting strange behaviour

**Comment by michaelklishin** [comment]
@danceasarxx you are asking me to investigate what is very likely an environment-specific problem. Monger has been around for over 5 years, hasn't changed much recently and is objectively a small library. If this was a general problem with Monger specifically then surely it would have been reported many times in the past. Sorry but I don't have the time to debug such issues for others.

**Comment by michaelklishin** [comment]
There is nREPL middleware in the stack trace: check what Leiningen or nREPL plugins may be in use and if disabling them makes any difference.

**Comment by michaelklishin** [comment]
`(require 'monger.core)` here takes less than a second on a 3+ year old MacBook Pro.

**Comment by danceasarxx** [comment]
After disabling everything, commenting out all other dependencies, deleting my entire maven repo so I could reinstall monger, it turns out `(clojure.core/load "/monger/conversion")` is the problem. So I restarted the repl and tried to load monger.conversion by myself and it proved me right. So what do you think it is in that namespace that's causing it to load slowly(I have checked the code, I can't see any IO there).
`

**Comment by danceasarxx** [comment]
And I am not here to question how long or how stable monger is I am trying to discover what the problem is. So unless you have another channel for discussion over this issue this is the only place I can report/discuss it.

**Comment by michaelklishin** [comment]
`monger.conversion` is a small namespace that defines a few protocols and imports most Java classes of them all. Either you have a lot of JARs on the classpath so there are many files to load and scan, or those JARs happen to be on a spinning drive (HDD), or something of that nature.

Only a profiler can tell. Use VisualVM's profiler as a starting point.

**Comment by michaelklishin** [comment]
Monger has a mailing list but since we already have a discussion here and it is marked as such (according to my habits, at least), it should stay here.

**Comment by danceasarxx** [comment]
Installed VVM, adjusted options. Started `lein repl` and connected the monitor and tried `(require 'monger.core)` and it took under a second(Algos is after me). Disconnected the VVM and the it was still the same. I actually did a lot of things before installing VisualVM, like deleting ~/.m2 again, assigning my hostname to loopback address(which seems irrelevant), and made my ring dependencies more specific(following ur assertion that classpath migth be the problem). Anyways thanks a lot
