### ISSUE TITLE
connect-with-credentials with auth database

### ISSUE THREAD

**Issue by rafamedina** [michaelklishin/monger#187]
Hi all

I'm trying to connect to a database with a user in auth source

```clojure
(let [db   "admin"
      u    "condo"
      p    (.toCharArray "password")]
  (mg/connect-with-credentials "127.0.0.1:27000/condo_dev" (mcred/for u db p))
```

The connection uri is:
`mongodb://condo:password@127.0.0.1:27000/condo_dev?authSource=admin`

But I'm getting this exception

```
java.lang.NullPointerException: null
        at monger.collection$find_one.invokeStatic(collection.clj:175) ~[na:na]
        at monger.collection$find_one.invoke(collection.clj:172) ~[na:na]
        at monger.collection$find_one_as_map.invokeStatic(collection.clj:185) ~[na:na]
        at monger.collection$find_one_as_map.invoke(collection.clj:182) ~[na:na]
```

I think I'm doing something wrong but I don't know what
Any help?

**Comment by rafamedina** [comment]
Update:
It has been working with the authsource == the database with connection string

`mongodb://condo:password@127.0.0.1:27000/condo_dev`

I mean: condo_dev?authSource=condo_dev
